spring:
  datasource:
    url: {JDBC_DATABASE_URL}
    username: {JDBC_DATABASE_USERNAME}
    password: {JDBC_DATABASE_PASSWORD}

algamoney:
  seguranca:
    enable-https: true
    origem-permitida: /**