spring:
  profiles:
    active: oauth-security
    group:
      prod: oauth-security
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://db:3306/algamoneyapi?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: algamoneyapi
    password: algamoneyapi
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    date-format: yyyy-MM-dd

logging:
  level:
    com:
      algaworks:
        algamoney: DEBUG

algamoney:
  s3:
    access-key-id: 123
    secret-access-key-id: 123
  mail:
    host: smtp.gmail.com
    port: 587
    username: ##email
    password: ##senha
